### PR TITLE
Always loads the complete facet list

### PR DESCRIPTION
**Pull request by jauco**
Even when a query result is provided in the props.

### CODE REVIEW

**Comment by Gijsjan** [comment]
Sorry, bit late to the game. If I understand correctly, the problem is keeping state on route change? I solved this by passing the last query as the query prop.

```
<FactetedSearch query={search.queries.last()} />
```

I would prefer this method above extra fetches. Let me know if that works for you.

About the extra dep (adehun). I would prefer to use `babel-polyfill`, but adding that would weigh in at 250kBs extra! Adehun adds 5kBs, so untill we can add single babel-polyfill modules (I know about core-js, but this seems too much hassle to me), I think we should go with adehun.

**Comment by Gijsjan** [comment]
Ah, I'm getting confused now. `Core-js` is part of `babel-polyfill`, but nowhere is documented how to import a single module. Anyway, we should probably be using `babel-plugin-transform-runtime`, but here also, the documentation is lacking. Something to look into, maybe during a no-sprint-week?

**Comment by jauco** [comment]
I think that works if you want to go back to a previous query (using html5 history or something) but not when running a query based on the search parameters passed from the outside. For example: if you click on this link http://test.dutch-caribbean.huygens.knaw.nl/archive/results?q=(facetValues:((name:dynamic~Ss~Speriod,values:(1828_~F_1845))),sortParameters:((direction:asc,fieldname:dynamic~Ssort~Stitle),(direction:asc,fieldname:dynamic~Sk~Speriod)),term:%27%27) there is no `search.queries.last()`

Without this fix, that search would not show facets that have a facet count of zero. (Yes, it is annoying that timbuctoo does not send these facets to the frontend, yes this is being fixed on the timbuctoo side in the new api)

**Comment by Gijsjan** [comment]
I have the same use case for Marginal Scholarship. As you state, this should be fixed in Timbuctoo, not in the frontend FacetedSearch lib. That's why I would prefer to use a workaround. My workaround is to add a global `var SERVER_STATE = {...}` to the index.html which contains an initial search. The `SERVER_STATE` is fed to Redux. I usually already have a `SERVER_STATE` var, so the (technical) overhead is minimal.

At the moment, Marginal Scholarship does a request for the initial search results at page load (like you're proposing for the FS lib), but I would like to refactor that to using `SERVER_STATE`.

**Pull request closed without merging**
